### ISSUE TITLE
Tests fail in a fresh local clone

### ISSUE THREAD

**Issue by vadz** [gollum/gollum#1817]
**Describe the bug**

Tests don't pass out of the box because the test `lotr_migration` repository added in d5970d6274308b01153d3ae7edbe45a49409af99 seems to be invalid/incomplete.

**To Reproduce**

1. `git clone` gollum repository
2. `bundle install`
3. `bundle exec rake test` (possibly with `TEST=test/test_migrate.rb` appended).
4. See errors starting with `Error: test_change_spaced_filenames_to_hyphenated_filenames(4_x____5_x_tag_migrator): Rugged::RepositoryError: could not find repository from '/tmp/4_x____5_x_tag_migrator20220414-19916-qyphwk'` and a few more of the same form.

**Expected behavior**
The tests should pass. This doesn't happen apparently because `test/examples/lotr_migration.git` is not a valid Git repository, so it can't be cloned, e.g.
```
$ git clone test/examples/lotr_migration.git /tmp/foo
fatal: repository 'test/examples/lotr_migration.git' does not exist
```

The workaround I use for now is to set `CI=1` when running the tests to disable the failing ones.

**Environment Info**

```
% bundle exec gollum --versions
Gollum 5.2.3
Running on: x86_64-linux-gnu with Ruby version 2.7.4
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.1.3
Markdown rendering gem: kramdown
Other renderering gems:
```

**Comment by benjaminwil** [comment]
Thanks for reporting.

I can confirm I was never able to get `test_migrate.rb` to pass locally on `master`, but I can't confirm that `test/examples/lotr_migration.git` is not a valid git repository. Here's what happens when I try to clone it:

```
⅋ git clone test/examples/lotr_migration.git/ /tmp/foo
Cloning into '/tmp/foo'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 32 (delta 0), reused 32 (delta 0), pack-reused 0
Receiving objects: 100% (32/32), 13.36 KiB | 13.36 MiB/s, done.
```

I'm running git `v2.34.1`.

The branch associated with my open pull request, #1805, allows me run `test_migrate.rb` tests and have them pass.

**Comment by dometto** [comment]
Should be fixed in #1805 then :)

**Comment by vadz** [comment]
Sorry, this still doesn't work for me with the latest master (95d35d38daf0084ec325ddb597e5ec0bfcb8880d), although the error messages are completely different now, of course. But there are still 3 failing tests:
```
% bundle exec rake test
/usr/bin/ruby2.7 -I"lib:lib:test:." $PREFIX/gollum/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/gollum/views/test_locale_helper.rb" "test/test_allow_editing.rb" "test/test_app.rb" "test/test_compare.rb" "test/test_history_view.rb" "test/test_latest_changes_view.rb" "test/test_local_time_option.rb" "test/test_migrate.rb" "test/test_overview_view.rb" "test/test_page_view.rb" "test/test_template_cascade.rb" "test/test_unicode.rb"

# Running tests with run options --seed 58983:

.......................................................................................................EEE..................................

Finished tests in 2.318289s, 60.3894 tests/s, 175.9919 assertions/s.


Error:
4_x____5_x_tag_migrator#test_change_spaced_filenames_to_hyphenated_filenames:
Rugged::RepositoryError: could not find repository from '/tmp/4_x____5_x_tag_migrator20220430-2648382-13lqohe'
    $PREFIX/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1.2/lib/rugged_adapter/git_layer_rugged.rb:567:in `new'
    $PREFIX/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1.2/lib/rugged_adapter/git_layer_rugged.rb:567:in `initialize'
    $PREFIX/gollum-lib/lib/gollum-lib/git_access.rb:16:in `new'
    $PREFIX/gollum-lib/lib/gollum-lib/git_access.rb:16:in `initialize'
    $PREFIX/gollum-lib/lib/gollum-lib/wiki.rb:132:in `new'
    $PREFIX/gollum-lib/lib/gollum-lib/wiki.rb:132:in `initialize'
    $PREFIX/gollum/bin/gollum-migrate-tags:241:in `new'
    $PREFIX/gollum/bin/gollum-migrate-tags:241:in `<top (required)>'
    $PREFIX/gollum/test/test_migrate.rb:24:in `load'
    $PREFIX/gollum/test/test_migrate.rb:24:in `block in load_script'
    $PREFIX/gollum/test/test_migrate.rb:23:in `chdir'
    $PREFIX/gollum/test/test_migrate.rb:23:in `load_script'
    $PREFIX/gollum/test/test_migrate.rb:65:in `block (2 levels) in <top (required)>'

Error:
4_x____5_x_tag_migrator#test_migration_with_page_file_dir:
Rugged::RepositoryError: could not find repository from '/tmp/4_x____5_x_tag_migrator20220430-2648382-pf6qvu'
    $PREFIX/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1.2/lib/rugged_adapter/git_layer_rugged.rb:567:in `new'
    $PREFIX/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1.2/lib/rugged_adapter/git_layer_rugged.rb:567:in `initialize'
    $PREFIX/gollum-lib/lib/gollum-lib/git_access.rb:16:in `new'
    $PREFIX/gollum-lib/lib/gollum-lib/git_access.rb:16:in `initialize'
    $PREFIX/gollum-lib/lib/gollum-lib/wiki.rb:132:in `new'
    $PREFIX/gollum-lib/lib/gollum-lib/wiki.rb:132:in `initialize'
    $PREFIX/gollum/bin/gollum-migrate-tags:241:in `new'
    $PREFIX/gollum/bin/gollum-migrate-tags:241:in `<top (required)>'
    $PREFIX/gollum/test/test_migrate.rb:24:in `load'
    $PREFIX/gollum/test/test_migrate.rb:24:in `block in load_script'
    $PREFIX/gollum/test/test_migrate.rb:23:in `chdir'
    $PREFIX/gollum/test/test_migrate.rb:23:in `load_script'
    $PREFIX/gollum/test/test_migrate.rb:74:in `block (2 levels) in <top (required)>'

Error:
4_x____5_x_tag_migrator#test_repair_broken_links:
Rugged::RepositoryError: could not find repository from '/tmp/4_x____5_x_tag_migrator20220430-2648382-759pdu'
    $PREFIX/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1.2/lib/rugged_adapter/git_layer_rugged.rb:567:in `new'
    $PREFIX/gollum/vendor/bundle/ruby/2.7.0/gems/gollum-rugged_adapter-1.1.2/lib/rugged_adapter/git_layer_rugged.rb:567:in `initialize'
    $PREFIX/gollum-lib/lib/gollum-lib/git_access.rb:16:in `new'
    $PREFIX/gollum-lib/lib/gollum-lib/git_access.rb:16:in `initialize'
    $PREFIX/gollum-lib/lib/gollum-lib/wiki.rb:132:in `new'
    $PREFIX/gollum-lib/lib/gollum-lib/wiki.rb:132:in `initialize'
    $PREFIX/gollum/bin/gollum-migrate-tags:241:in `new'
    $PREFIX/gollum/bin/gollum-migrate-tags:241:in `<top (required)>'
    $PREFIX/gollum/test/test_migrate.rb:24:in `load'
    $PREFIX/gollum/test/test_migrate.rb:24:in `block in load_script'
    $PREFIX/gollum/test/test_migrate.rb:23:in `chdir'
    $PREFIX/gollum/test/test_migrate.rb:23:in `load_script'
    $PREFIX/gollum/test/test_migrate.rb:49:in `block (2 levels) in <top (required)>'

140 tests, 408 assertions, 0 failures, 3 errors, 0 skips
```

I think the tests (and `git clone`) might pass for you because you have an existing `test/examples/lotr_migration.git/refs/heads` directory. If I just `mkdir -p` it, the tests pass for me too, but without it they don't and I believe this is normal, as a valid Git repository must have a `refs` subdirectory.

And, of course, Git doesn't track empty directories, so this directory is _not_ present in the repository.

**Comment by benjaminwil** [comment]
Okay, I understand now. I think I can fix this.

**Comment by benjaminwil** [comment]
I've created a PR, #1821, that resolves the issue, and even runs the `test_migrate` tests in CI. It's possible there are other things that make these git repositories invalid; perhaps they were never generated using `git`. That said, this change is good–Gollum test suite is in better and better shape all the time. ✨

**Comment by benjaminwil** [comment]
I should add that I was able to reproduce your issue with a fresh clone! It didn't occur to me that I should have done that the first time. My apologies.

**Comment by vadz** [comment]
Thanks for returning to and fixing this! I can confirm that all tests pass now (I still get a bunch of warnings, but this can be fixed by applying https://github.com/gollum/gollum-lib/pull/417 and pointing gollum to use a local gollum-lib).
