### ISSUE TITLE
docker gollumwiki/gollum:master crashes

### ISSUE THREAD

**Issue by alexander-zimmermann** [gollum/gollum#1858]
Since the last commit on 13.09.22 to [gollumwiki/gollum:master]([master](https://registry.hub.docker.com/layers/gollumwiki/gollum/master/images/sha256-fb426b78848e8f01f9d3a9e6b230b7a48f824740329985d3eb50508fa3e35b90?context=explore)) the docker container crashes

```bash
alexander@ubuntu:~$ docker start -a gollum 
WARNING: Mathjax will soon be disabled by default. To explicitly enable it, use --mathjax
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
	from /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/gollum-5.3.0/lib/gollum/assets.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/gollum-5.3.0/lib/gollum/app.rb:16:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/gollum-5.3.0/bin/gollum:279:in `<top (required)>'
	from /usr/local/bundle/bin/gollum:23:in `load'
	from /usr/local/bundle/bin/gollum:23:in `<main>'
```

Please let me know if I need to report the bug somewhere else.

BR
Alex

**Comment by dometto** [comment]
Should be fixed in the latest Docker image.

**Comment by focmb** [comment]
The issue is still there

`➜ docker run --rm -p 4567:4567 -v /containers/gollum:/wiki gollumwiki/gollum:master
Unable to find image 'gollumwiki/gollum:master' locally
master: Pulling from gollumwiki/gollum
213ec9aee27d: Already exists 
20b722058550: Pull complete 
4e4edad8fe58: Pull complete 
94ad700a4b03: Pull complete 
df6ba56b0976: Pull complete 
e85b8f74fd5e: Pull complete 
f094f4be7b4f: Pull complete 
3e74b288a4cb: Pull complete 
c8f3baa27ac9: Pull complete 
Digest: sha256:dfc54858d9d17c66afaa9a5c83e4c64bacf5cfc827944afb6619ef5f35545bd2
Status: Downloaded newer image for gollumwiki/gollum:master
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /wiki/.git/
WARNING: Mathjax will soon be disabled by default. To explicitly enable it, use --mathjax
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
	from /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/gollum-5.3.0/lib/gollum/assets.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/gollum-5.3.0/lib/gollum/app.rb:16:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/gollum-5.3.0/bin/gollum:279:in `<top (required)>'
	from /usr/local/bundle/bin/gollum:23:in `load'
	from /usr/local/bundle/bin/gollum:23:in `<main>'
`

Running this command at 12:20 today (german time UTC+1)

**Comment by dometto** [comment]
Looks like you may have been just a bit too fast, the latest image only just appeared on Dockerhub. When I pull/run locally it works. Mind giving it another try?

**Comment by alexander-zimmermann** [comment]
@dometto Thanks for the fix! My pipeline get triggered this night to pull the image. Will come back w/ feedback.

**Comment by focmb** [comment]
you are right. now it works. thanx

**Comment by alexander-zimmermann** [comment]
Confirmed ;-)
