### ISSUE TITLE
pages named like internal routes don't display

### ISSUE THREAD

**Issue by goblin** [gollum/gollum#630]
If you name your page like `fileview.md` or `pages.md`, you can't view it. Following a link to it will get you to the specially-generated view that lists all files or pages. Adding `--base-path` doesn't help (if I use `--base-path wiki` then the internal links become `/wiki/fileview` which IMO should display the page and the special file-view display should perhaps be at `/fileview`)

**Comment by bartkamphorst** [comment]
@dometto Actually, part of this issue has been resolved in `5.x` with the change in filename extension handling. `http://localhost:4567/pages.md` would show the page `pages.md` if it exists (I had to create it on the cli though; the webinterface wouldn't do it).

**Comment by dometto** [comment]
That's true, but if you have a page `latest_changes.md` and attempt to access it via `localhost/latest_changes`, (as opposed to `localhost/latest_changes.md` that would still not work. Do you think it would make sense to introduce the `gollum` namespace to make that work, too? I think I have  PR branch lying around somewhere that implements it.

**Comment by bartkamphorst** [comment]
I actually don't mind that behavior too much. Previously, there was no way at all of displaying pages that were named the same as internal routes, and I can see why that would be annoying (and brittle, because any additional internal routes that developers might add (e.g., `/overview`) could suddenly cause issues for all wikis that had an `overview.md` page in their root). Having a direct way of viewing these pages anyway is good enough for me. @goblin Do you have an opinion about this?

**Comment by goblin** [comment]
It's been a while :-)

Yeah, most of my original problem was due to having an unclean namespace for user-defined pages, like @bartkamphorst mentioned.

Having an option to force to view your page by adding .md to the URL is indeed better than nothing, but can still cause issues for people who weren't careful enough to add that extension to every page they link to.

So ideally, I still think the internal routes should have a different path to the user-supplied ones.

**Comment by bartkamphorst** [comment]
Thanks for chiming in @goblin 👍 . Okay, I'm adding this as a todo for the 5.x branch.

**Comment by bartkamphorst** [comment]
Seems like this is fixed in https://github.com/gollum/gollum/pull/1328 ! 🎉  Works like a charm, @dometto !

**Comment by dometto** [comment]
Yay! 🎆
